config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :campaigns
  resources :banners
  resources :banner_videos
  resources :targets
  resources :rtb_standards
  resources :documents
  resources :categories
  resources :users
  resources :attachments
  resources :lists

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/myaccount' => 'users#myaccount'
  patch '/myaccountUpdate' => 'users#myaccountUpdate'
  
  root 'dashboards#home'
  get '/' => 'dashboards#home'
  get 'dashboards/campaigndetail' => 'dashboards#campaigndetail'  
  
  get 'dashboards' => 'dashboards#home'
  get 'dashboards/home' => 'dashboards#home'
  
  get 'reports' => 'reports#home'
  get 'reports/home' => 'reports#home'
  
  get 'getCampaignDates' => 'campaigns#getDates'
  get 'getExchangeAttributes' => 'campaigns#getExchangeAttributes'
  get 'biddersSynchAll' => 'campaigns#biddersSynchAll'
  
  get 'duplicatedoc' => 'documents#duplicate'
  get 'duplicatertb_standard' => 'rtb_standards#duplicate'  
  
  get 'help' => 'help#list'
  get 'help/list' => 'help#list'
  get 'help/open' => 'help#open'
  
  post '/attachments/create' => 'attachments#create'
  
  post "/lists/upload" => "lists#upload"


 namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
      namespace :report do
        post 'summary'
        get 'summary'
      end
    end
  end  
  
end

app/models/target.rb
class Target < ActiveRecord::Base

    has_many :campaigns
    has_many :banners
    has_many :banner_videos
    belongs_to :list, :foreign_key => :domains_list_id
    
    before_update :set_updated_at
    after_update :set_campaign_updated_at
    after_create :set_campaign_updated_at
    
    validates :name,:activate_time,:expire_time, :presence => true
    validate :expire_time_cannot_be_in_the_past
    
    def set_updated_at
       self.updated_at = Time.now         
    end        

    def set_campaign_updated_at       
         if campaigns=self.campaigns  
            campaigns.each do |campaign|
                campaign.set_updated_at
                campaign.save
            end
        end
    end

    def expire_time_cannot_be_in_the_past
        if expire_time.present? && expire_time < Time.now
          errors.add(:expire_time, "can't be in the past")
        end
        if activate_time.present? && expire_time.present? && activate_time > expire_time
          errors.add(:expire_time, "can't be before activate time")
        end
    end  


    def check_time    
        if  (activate_time=self.activate_time and activate_time > Time.now) or 
            (expire_time=self.expire_time and expire_time < Time.now)   
        then    
            return false
        end
        return true
    end        

    def check_errors
        errors = []
        #if not self.check_time
        #    errors.push("Target active time is not in current time.") 
        #end
      #  puts "Checking expire_time #{self.expire_time.to_i}, now #{Time.now.to_i}"
        if self.expire_time and (self.expire_time < Time.now) 
            errors.push("Expire time in the past.")
        end
        if self.activate_time and (self.activate_time > Time.now) 
            errors.push("Activate time in the future.")
        end
        errors
    end

    
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController

  before_action :set_target, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  
  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.order(:name)
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
    @target.activate_time ||= Time.now
    @target.expire_time ||= Time.now
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = Target.new(target_params)
    respond_to do |format|
      if @target.save
        # No need to update campaigns. Targets are assigned in Campaign edit.
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      old_camp_ids = @target.campaigns.collect{|c| c.id.to_s}      
      if @target.update(target_params)
        notice = 'Target was successfully updated.'
        new_camp_ids = @target.campaigns.collect{|c| c.id.to_s}      
        old_camp_ids ||= []
        new_camp_ids ||=[]
        new_camp_ids += old_camp_ids
        new_camp_ids.uniq!   # List all campaigns to update
        # Update bidder for old and new campaign 
        new_camp_ids.each do |id|              
            if campaign = Campaign.find_by_id(id) 
              puts "Update campaign #{id}"
              if not campaign.update_bidder
                notice += ' <span class="text-danger">Error on bidder synch process. Please try again.</span>'
                break
              end
            end
        end 
        format.html { redirect_to @target, notice: notice }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    old_campaigns = @target.campaigns 
    notice = ""
    if not Bidder.ping
      notice = '<span class="text-danger">Error. Unable to connect to bidder. Check staus and try again.</span>'
    else  
      if @target.destroy
        notice += 'Target was successfully destroyed.'
        old_campaigns.each do |c| 
            c.update_bidder 
        end if old_campaigns 
      else
        notice += '<span class="text-danger">Database error. Please try again.</span>'  
      end
    end
    respond_to do |format|
      format.html { redirect_to targets_url, notice: notice  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end


    def target_params
      # translate datetimepicker
      if str = params[:activate_time] 
        params[:target][:activate_time] = Time.strptime(str, "%m/%d/%Y %H:%M")       
      end
      if str = params[:expire_time] 
        params[:target][:expire_time] =  Time.strptime(str, "%m/%d/%Y %H:%M")  
      end
      if params[:target] and list=params[:target][:list_of_domains]
          params[:target][:list_of_domains] = list.to_s.split(/\s+/).join(",")
      end      
    # Translate param arrays to comma separated strings
      ["country","devicetype","IAB_category","IAB_category_blklist"].each do |attr|
        str = params[attr]
        str = str.join(",") if str.kind_of?(Array)
        params[:target][attr] = str.to_s
      end
      if params[:target] and not params[:target][:domains_list_id].to_s.empty? and list=List.find_by_id(params[:target][:domains_list_id])        
        params[:target][:list_of_domains] = "$#{list.name}"
      end
      params.require(:target).permit(:name, :id, :activate_time, :expire_time, :list_of_domains, :domains_list_id,
        :domain_targetting, :geo_latitude,:geo_longitude, :geo_range, :country, :geo_region, :carrier, :os, :make, :model,
        :devicetype,:IAB_category,:IAB_category_blklist,:created_at, :updated_at )
    end





end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= bootstrap_form_for(@target,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2
      <ul>
      <% @target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  

  <%= f.text_field :name, label: "Target Name" , class: "input-sm" %>
  <%= f.text_field :id, label: "Target ID" , class: "input-sm", readonly: true %>
  <div class="form-group">
      <label class="control-label col-sm-2 required" for="activate_time">Active Start/End</label>
      <div class="col-sm-10 form-inline">
          <div class='input-group datepicker'>
              <input type='text' class='input-sm' name='activate_time' value="<%=@target.activate_time.strftime('%m-%d-%Y %H%M')%>"/>
              <span class="input-group-addon  input-sm">
                  <span class="glyphicon glyphicon-calendar "></span>
              </span>
          </div>
          &nbsp;&nbsp;to&nbsp;&nbsp;
          <div class='input-group datepicker'>
              <input type='text' class='input-sm' name='expire_time' value="<%=@target.expire_time.strftime('%m-%d-%Y %H%M')%>" />
              <span class="input-group-addon  input-sm">
                  <span class="glyphicon glyphicon-calendar "></span>
              </span>
          </div>
      </div>
  </div>  
  <%= f.select :domain_targetting,  [ ["Blacklist","blacklist"],["Whitelist","whitelist"]]  ,{  label: "Domain List Type", "include_blank" => true},{class: "input-sm nosearch" } %>
  <%= f.text_area :list_of_domains, label: "Domains Values", class: "input-sm" %>
  <%= f.select :domains_list_id, List.all.collect { |v| [ v[:name], v[:id] ] },{ label: "Use Set as Domain List",include_blank: true}, {class: "input-sm search_single"} %>  
  <hr/>
  <div class="col-sm-2"></div>
  <div class="col-sm-10">
    <span class="badge badge-blue mapdialog crosshair" title="Set lat, long and range using a map.">Open Map</span>
  </div>
  <%= f.text_field :geo_latitude, append: "degrees", input_group_class: 'input-group-sm' %>  
  <%= f.text_field :geo_longitude, append: "degrees", input_group_class: 'input-group-sm' %>  
  <%= f.number_field :geo_range, append: "meters", input_group_class: 'input-group-sm' %>
  <hr/>
  <%= f.text_field :geo_region, class: 'input-sm' %>
  
  <%= render :partial => 'form_csv', 
            :locals => {
                :value => @target[:country], 
                :label => "Country",
                :tag_id => "country[]",
                :collection=> Country.where("country_type='Independent State' OR country_type='Proto Independent State'").order(:common_name).collect{|v| [v[:common_name],v["iso_3166-1_3_letter_code"]]}
            } 
  %>
  
  <%= f.text_field :carrier, class: 'input-sm' %>
  <%= f.text_field :os, label: "Operating System", class: 'input-sm' %>
  <%= f.text_field :make, class: 'input-sm' %>
  <%= f.text_field :model, class: 'input-sm' %>

  <%= render :partial => 'form_csv', 
            :locals => {
                :value => @target[:devicetype], 
                :label => "Device Type",
                :tag_id => "devicetype[]",
                :collection=>DeviceType.all.sort_by {|obj| obj[:description]}.collect { |v| [ v[:description], v[:value] ] } 
            } 
  %>

  <%= render :partial => 'form_csv', 
            :locals => {
                :value => @target[:IAB_category], 
                :label => "IAB Categories - Whitelist",
                :tag_id => "IAB_category[]",
                :collection=>IabCategory.all.collect { |v| [ "#{v[:iab_id]} - #{v[:name]}", v[:iab_id] ] } 
            } 
  %>
  
  <%= render :partial => 'form_csv', 
            :locals => {
                :value => @target[:IAB_category_blklist], 
                :label => "IAB Categories - Blacklist",
                :tag_id => "IAB_category_blklist[]",
                :collection=>IabCategory.all.collect { |v| [ "#{v[:iab_id]} - #{v[:name]}", v[:iab_id] ] } 
            } 
  %>
  
  <div class="actions">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <button type="submit" class="btn btn-default btn-sm">Update</button>
    </div>
  </div>  
	<script 
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDsr2OKHmwGSG7WzW0UPFfowq2sbJ7FrwA">
  </script>
  
<% end %>

app/views/targets/_form_csv.html.erb
 <div class="form-group">
    <label class="control-label col-sm-2" for="<%=tag_id%>"><%=label%></label>
    <div class="col-sm-10">
      <%= select_tag tag_id,
          options_for_select( 
            collection,
            value.to_s.split(",")
          ), 
          {  multiple: "multiple", class:"form-control search"} 
      %>
    </div>
  </div>

app/views/targets/_showform.html.erb
<%= bootstrap_form_for(@target,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2
      <ul>
      <% @target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.text_field :id, label: "ID" , class: "input-sm",disabled: true %>

  <%= f.text_field :name, label: "Target Name" , class: "input-sm",disabled: true %>
  <%= f.text_field :id, label: "Target ID" , class: "input-sm", readonly: true %>

 <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @target[:activate_time], 
                :label => "Activate Time",
            } 
  %>  

 <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @target[:expire_time], 
                :label => "Expire Time",
            } 
  %>  
  
  <%= f.text_field :domain_targetting, label: "Domain List Type", class: "input-sm", readonly: true %>
  <%= f.text_area :list_of_domains, label: "List of Domains",class: "input-sm", readonly: true %>
  
  <%= f.text_field :geo_latitude, append: "degrees", input_group_class: 'input-group-sm', readonly: true %>  
  <%= f.text_field :geo_longitude, append: "degrees", input_group_class: 'input-group-sm', readonly: true %>  
  <%= f.number_field :geo_range, append: "meters", input_group_class: 'input-group-sm' , readonly: true%>
  <%= f.text_field :geo_region, class: 'input-sm' , readonly: true %>
  
   <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @target[:country], 
                :label => "Country",
            } 
  %>  
  
  <%= f.text_field :carrier, class: 'input-sm', readonly: true %>
  <%= f.text_field :os, label: "Operating System", class: 'input-sm', readonly: true %>
  <%= f.text_field :make, class: 'input-sm', readonly: true %>
  <%= f.text_field :model, class: 'input-sm', readonly: true %>
  
  <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @target[:devicetype], 
                :label => "Device Type",
            } 
  %> 
  
  <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @target[:IAB_category], 
                :label => "IAB Categories - Whitelist",
            } 
  %>

  <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @target[:IAB_category_blklist], 
                :label => "IAB Categories - Blacklist",
            } 
  %>
    

  
<% end %>

app/views/targets/_showform_textrow.html.erb
<div class="form-group">
    <% name="" %>
    <label class="control-label col-sm-2"><%=label%></label>
    <div class="col-sm-10"><%= text_field_tag(name, value, {class:"form-control input-sm", readonly: true }) %></div>
</div>

app/views/targets/_stats.html.erb
<table class="table table-striped table-bordered table-hover">
    <tbody>
    <% if errors = @target.check_errors and not errors.empty? %>    
        <tr>
            <td>Status</td>
            <td>
                <span class="text text-danger"><%=errors.join("<br/>")%></span>
            </td>
        </tr>
    <%end%>
    <tr>
        <td>Last updated</td>
        <td><%=@target.updated_at%></td>
    </tr>
    <tr>
        <td>Created</td>
        <td><%=@target.created_at%></td>
    </tr>
    </tbody>
</table> 

app/views/targets/edit.html.erb
 <% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                Edit Target: <em> <%=@target.name%> </em></div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/targets#">Targets</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Edit</li>
        </ol>
 <%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="row mtl">
                <div class="col-md-3">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Profile
                        </div>
                        <div class="panel-body pan">
                            <%= render 'stats' %>
                        </div>
                    </div>
                </div>    
                <div class="col-md-9">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Edit
                        </div>
                        <div class="panel-body pan">
                            <%= render 'form' %>
                            <%= link_to 'Targets', targets_path , class:"btn btn-default btn-sm"%>        
                        </div>
                    </div>                            
                </div>
            </div>
        </div>

<%end%>

app/views/targets/index.html.erb
 <% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Targets</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Targets</li>
        </ol>
<%end%>

<% content_for :main_body do %> 	
      <style>a:focus { color: green !important; }</style>
      <%= link_to 'New target', new_target_path  , class:"btn btn-default btn-sm" %>
      <table class="table table-striped table-hover" id="listtable">
        <thead>
          <tr >            
            <th>ID</th>
            <th>Target Name</th>
            <th>Status</th>
            <th>Campaigns</th>
            <th>Exchanges</th>
            <th width="3%"></th>
            <th width="3%"></th>
            <th width="3%"></th>
          </tr>
        </thead>
        <tbody>
          <% @targets.each do |target| %>
            <tr>
              <td><%=target.id%></td>
              <td><%=target.name%></td>
              <td>
                <% if errors = target.check_errors and not errors.empty?
                     str = errors.join("<br/>")
                %>
                      <span class="text text-danger"><%=raw(str)%></span>
                <%end%>  
              </td>
              <td>
                  <%if target.campaigns  %>
                    <% target.campaigns.each do |campaign|%>
                       <%=campaign.name%> (<%= link_to "ID #{campaign.id}", campaign_path(campaign)%>)<br/>
                    <%end%>
                  <%end%>
              </td>
              <td>
                  <%if target.campaigns  %>
                    <% target.campaigns.each do |campaign|%>
                        <%= raw(campaign.exchanges.split(",").collect{|e| e.camelize}.join("<br/>")) if campaign.exchanges %>
                    <%end%>
                  <%end%>
              </td>
              <td><%= link_to 'Show',target   %></td>
              <td><%= link_to 'Edit', edit_target_path(target)  %></td>
              <td><%= link_to 'Destroy', target, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
     

<%end%>

app/views/targets/new.html.erb
<% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                New Target
            </div>
        </div>
    <ol class="breadcrumb page-breadcrumb pull-right">
        <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li><a href="/targets#">Targets</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="active">New</li>
    </ol>
<%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="panel panel-violet">
                <div class="panel-heading">
                    New
                </div>
                <div class="panel-body pan">
                    <%= render 'form' %>
                    <%= link_to 'Targets', targets_path , class:"btn btn-default btn-sm"%>        
                </div>
            </div>                            
        </div>
<%end%>

app/views/targets/show.html.erb
<% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                Show Target: <em> <%=@target.name%> </em></div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/targets#">Targets</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Show</li>
        </ol>
<%end%>
<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="row mtl">
                <div class="col-md-3">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Profile
                        </div>
                        <div class="panel-body pan">
                            <%= render 'stats' %>
                        </div>
                    </div>
                </div>    
                <div class="col-md-9">
                    <div class="panel panel-grey">
                        <div class="panel-heading">
                            Show
                        </div>
                        <div class="panel-body pan">
                            <%= render 'showform' %>
                             <%= link_to 'Edit', edit_target_path(@target) , class:"btn btn-default btn-sm" %> |
                    <%= link_to 'Targets', targets_path , class:"btn btn-default btn-sm"%>            
                        </div>
                    </div>                            
                </div>
            </div>
        </div>
<%end%>