config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :campaigns
  resources :banners
  resources :banner_videos
  resources :targets
  resources :rtb_standards
  resources :documents
  resources :categories
  resources :users
  resources :attachments
  resources :lists

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/myaccount' => 'users#myaccount'
  patch '/myaccountUpdate' => 'users#myaccountUpdate'
  
  root 'dashboards#home'
  get '/' => 'dashboards#home'
  get 'dashboards/campaigndetail' => 'dashboards#campaigndetail'  
  
  get 'dashboards' => 'dashboards#home'
  get 'dashboards/home' => 'dashboards#home'
  
  get 'reports' => 'reports#home'
  get 'reports/home' => 'reports#home'
  
  get 'getCampaignDates' => 'campaigns#getDates'
  get 'getExchangeAttributes' => 'campaigns#getExchangeAttributes'
  get 'biddersSynchAll' => 'campaigns#biddersSynchAll'
  
  get 'duplicatedoc' => 'documents#duplicate'
  get 'duplicatertb_standard' => 'rtb_standards#duplicate'  
  
  get 'help' => 'help#list'
  get 'help/list' => 'help#list'
  get 'help/open' => 'help#open'
  
  post '/attachments/create' => 'attachments#create'
  
  post "/lists/upload" => "lists#upload"


 namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
      namespace :report do
        post 'summary'
        get 'summary'
      end
    end
  end  
  
end

app/models/banner.rb
class Banner < ActiveRecord::Base
    
    belongs_to :campaign
    belongs_to :target
    has_and_belongs_to_many :rtb_standards
    has_many :report_commands
    has_many :exchange_attributes, dependent: :destroy
    
    validates :name, :interval_start,:interval_end,:iurl,:htmltemplate,:contenttype , :presence => true
    validates :bid_ecpm,  :numericality => { :allow_blank => false }, :presence => true
    validate :interval_end_cannot_be_in_the_past
    
    validates_format_of :width_range, :with => /\A\d+-\d+\Z/ , :allow_blank => true,  message: "Invalid format. Must be <number>-<number>" 
    validates_format_of :height_range, :with =>/\A\d+-\d+\Z/, :allow_blank => true,    message: "Invalid format. Must be <number>-<number>" 
    validates_format_of :width_height_list, :with => /\A[\dx,]+\Z/, :allow_blank => true,    message: "Invalid format. Must be <number>x<number>,<number>x<number>,..." 
    
    
    
    before_update :set_updated_at
    after_update :set_campaign_updated_at
    after_create :set_campaign_updated_at
    
    def interval_end_cannot_be_in_the_past
        if interval_end.present? && interval_end < Time.now
          errors.add(:interval_end, "can't be in the past")
        end
        if interval_end.present? && interval_start.present? && interval_end < interval_start
          errors.add(:interval_end, "can't be before interval start")
        end
    end            

    def check_errors
        errors = []
        # Check budget versus cost
        if cost=self.total_cost and budget=self.total_basket_value and 
           cost.to_f>0 and 
           (cost.to_f > budget.to_f) 
        then
            errors.push("Total cost #{sprintf('%.2f', cost)} greater than budget #{sprintf('%.2f', budget)}")
        end
        if cost=self.daily_cost and budget=self.daily_budget and 
           cost.to_f>0 and 
           (cost.to_f > budget.to_f) 
        then
            errors.push("Daily cost #{sprintf('%.2f', cost)} greater than budget #{sprintf('%.2f', budget)}")
        end
        if cost=self.hourly_cost and budget=self.hourly_budget and 
           cost.to_f>0 and 
           (cost.to_f > budget.to_f) 
        then
            errors.push("Daily cost #{sprintf('%.2f', cost)} greater than budget #{sprintf('%.2f', budget)}")
        end
            
      #  puts "Checking expire_time #{self.expire_time.to_i}, now #{Time.now.to_i}"
        if self.interval_end and (self.interval_end < Time.now) 
            errors.push("Interval end time expired!")
        end
        if self.interval_start and (self.interval_start > Time.now) 
            errors.push("Interval start time not yet active.")
        end
        errors
    end

    def set_updated_at
       self.updated_at = Time.now         
    end

    def set_campaign_updated_at       
        if campaign = self.campaign
            campaign.set_updated_at
            campaign.save
        end
    end

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  before_filter :authorize

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.order(:name)
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
    @banner.frequency_spec = "device.ip" if @banner.frequency_spec.to_s.empty?
    @banner.interval_start ||= Time.now
    @banner.interval_end ||= Time.now
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)
    exchange_attributes_params
    respond_to do |format|
      if @banner.save
        notice = 'Banner was successfully created.'       
        notice +=  ' <span class="text-danger">Error on bidder synch process. Please try again.</span>' if @banner.campaign and not @banner.campaign.update_bidder
        format.html { redirect_to @banner, notice: notice }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      old_campaign = @banner.campaign
      if @banner.update(banner_params)
        @banner.exchange_attributes.delete_all if @banner.exchange_attributes
        exchange_attributes_params
        notice = 'Banner was successfully updated.' 
        # Update bidder for old and new campaign 
        if old_campaign and 
          ( 
            not @banner.campaign or                                     # campaign removed
            not @banner.campaign.id.to_s.eql?(old_campaign.id.to_s)     # campaign changed
          )
          then
            puts "Update previous campaign #{old_campaign.id.to_s}"
            old_campaign.update_bidder           
        end
        if @banner.campaign and not @banner.campaign.update_bidder 
            notice += ' <span class="text-danger">Error on bidder synch process. Please try again.</span>'
        end        
        format.html { redirect_to @banner, notice: notice }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    old_campaign = @banner.campaign
    notice = ""
    if not Bidder.ping
      notice = '<span class="text-danger">Error. Unable to connect to bidder. Check staus and try again.</span>'
    else
      if @banner.destroy
        notice = 'Banner was successfully destroyed.' 
        old_campaign.update_bidder  if old_campaign
      else
        notice = '<span class="text-danger">Bidder updated but database error. Please try again.</span>'
      end
    end
    respond_to do |format|
      format.html { redirect_to banners_url, notice: notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      
      # Convert datepicker strings to time objects
      if str = params[:interval_start] 
        params[:banner][:interval_start] = Time.strptime(str, "%m/%d/%Y %H:%M")     #"11/17/2016 1:37 PM"      
      end
      if str = params[:interval_end] 
        params[:banner][:interval_end] =  Time.strptime(str, "%m/%d/%Y %H:%M")  
      end
      
      if params[:size_match_type].eql?("none")
          params[:banner][:height] = nil
          params[:banner][:width] = nil
          params[:banner][:width_range] = nil
          params[:banner][:height_range] = nil
          params[:banner][:width_height_list] = nil          
      elsif params[:size_match_type].eql?("width_height_only")
          params[:banner][:width_range] = nil
          params[:banner][:height_range] = nil
          params[:banner][:width_height_list] = nil         
      elsif params[:size_match_type].eql?("width_height_range")
          params[:banner][:height] = nil
          params[:banner][:width] = nil
          params[:banner][:width_range].gsub!(/\s/,"")
          params[:banner][:height_range].gsub!(/\s/,"")           
          params[:banner][:width_height_list] = nil                  
      elsif params[:size_match_type].eql?("width_height_list")
          params[:banner][:height] = nil
          params[:banner][:width] = nil
          params[:banner][:width_range] = nil
          params[:banner][:height_range] = nil
          params[:banner][:width_height_list].gsub!(/\s/,"")           
      end      
      
      # Convert deals to format id:price,id:price,....
      if params[:deal_type].eql?("none")
          params[:banner][:deals] = ""      
      elsif params[:deal_id] and params[:deal_price]
          # Create deals field
          dealsAry = []
          params[:deal_id].each_with_index do |id,index| 
              dealsAry.push("#{id}:#{params[:deal_price][index]}") if not id.to_s.empty? and params[:deal_price][index] 
          end
          if params[:deal_type].eql?("private_only")
              params[:banner][:bid_ecpm] = 0
          end
          params[:banner][:deals] = dealsAry.join(",")
      end
      
      params.require(:banner).permit(:campaign_id,:id, :name, :updated_at,:created_at,:interval_start, :interval_end,
        :total_basket_value, :daily_budget,:hourly_budget, :bid_ecpm, :contenttype, :iurl, :htmltemplate, :targetting, :width, :height, 
        :width_range, :height_range, :width_height_list,
        :frequency_spec,:frequency_expire,:frequency_count ,:target_id, :deals, :rtb_standard_ids=>[])
    end


    def exchange_attributes_params
        if params[:exchange_attributes] and params[:exchange_attributes_exchange]
          params[:exchange_attributes].each do |exchg|
            exchg.each_with_index do |(name,val),idx|                
                @banner.exchange_attributes << ExchangeAttribute.create( 
                      name: name , 
                      value: val, 
                      exchange: params[:exchange_attributes_exchange][idx]
                ) if params[:exchange_attributes_exchange][idx]
            end
          end        
        end

    end

end

app/helpers/banner_helper.rb
module BannerHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_exchange_attributes.html.erb
     <%
            attrObj.keys.each do |exchg| 
               if exchgObj=Exchange.find_exchange(exchg) and exAttributes = exchgObj[:attributes]
                  attrHash = attrObj[exchg]
                
      %>
                    <div class="form-group">
                        <label class="control-label col-sm-2"> <%=exchg.upcase%> Exchange Attributes</label>                         
                        <div class="col-sm-10">      

                            <table class="table">
                            <% exAttributes.each do |attrObj| %>

                                <%  
                                      attrVal = attrObj[:value]
                                      attrVal = attrHash[attrObj[:name]] if attrHash[attrObj[:name]]
                                %>

                                <tr>
                                      <td width="20%">
                                        <%=attrObj[:label]%> 
                                      </td>
                                      <td>
                                        <% if attrObj[:form_type].to_s.eql?("input")    %>                                                          
                                            <input type="hidden" name="exchange_attributes_exchange[]" value="<%=exchg%>"/>
                                            <input type="text" class="input-sm form-control" name="exchange_attributes[][<%=attrObj[:name]%>]" value="<%=attrVal%>"/>
                                                                                        
                                        <% elsif attrObj[:form_type].to_s.eql?("select")  %>   
                                            <input type="hidden" name="exchange_attributes_exchange[]" value="<%=exchg%>"/>
                                            <select class="input-sm form-control nosearch" name="exchange_attributes[][<%=attrObj[:name]%>]">
                                                <% sel = { attrVal.to_s => "SELECTED" } %>
                                                <option value=""></option>
                                                <% attrObj[:select_options].sort{ |a,b| a[:label].downcase <=> b[:label].downcase }.each do |opt|  %>
                                                    <option value="<%=opt[:value]%>" <%=sel[opt[:value].to_s].to_s%>><%=opt[:label]%></option>  
                                                <%end%>
                                            </select>
                                            
                                        <% elsif attrObj[:form_type].to_s.eql?("select_multi")  %>   
                                            <input type="hidden" name="exchange_attributes_exchange[]" value="<%=exchg%>"/>
                                            <select class="input-sm form-control search_rules" name="exchange_attributes[][<%=attrObj[:name]%>][]" multiple>
                                                <% selVals = []                                                
                                                   selVals =  JSON.parse(attrVal) if not attrVal.to_s.empty?  
                                                %>
                                                <option value=""></option>
                                                <% attrObj[:select_options].sort{ |a,b| a[:label].downcase <=> b[:label].downcase }.each do |opt|  %>
                                                    <% 
                                                        sel = ""
                                                        sel = "SELECTED" if selVals.include?(opt[:value])
                                                    %>
                                                    <option value="<%=opt[:value]%>" <%=sel%>><%=opt[:label]%></option>  
                                                <%end%>
                                            </select>

                                        <%end%>
                                      </td>                          
                                </tr>
                            <%end%>
                            </table>


                        </div>
                    </div>
              <%end%>
          <%end%>

app/views/banners/_showform.html.erb
<%= bootstrap_form_for(@banner,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2
      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%  
      if @banner[:campaign_id] and camp = Campaign.find(@banner[:campaign_id])
          campname = camp.name
      else
         campname = "" 
      end
  %>
    <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => campname, 
                :label => "Campaign",
            } 
  %>
  <%= f.text_field :id, label: "Banner ID" , class: "input-sm",readonly: true %>
  <%= f.text_field :name, label: "Banner Name" , class: "input-sm",readonly: true %>
  <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @banner[:interval_start], 
                :label => "Interval Start",
            } 
  %>  

 <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @banner[:interval_end], 
                :label => "Interval End",
            } 
  %>  

  <%= f.number_field :width, append: "pixels", input_group_class: 'input-group-sm',readonly: true %>
  <%= f.number_field :height, append: "pixels", input_group_class: 'input-group-sm',readonly: true %>
  <%= f.text_field :width_range, class: 'input-sm', readonly: true %>
  <%= f.text_field :height_range, class: 'input-sm', readonly: true %>
  <%= f.text_field :width_height_list, class: 'input-sm', readonly: true %>
  <%= f.number_field :bid_ecpm, prepend: "$", input_group_class: 'input-group-sm',readonly: true %>  
   <%= f.text_field :deals, class: 'input-sm', readonly: true %>  
  <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @banner[:contenttype], 
                :label => "Content Type",
            } 
  %>
  <%= f.text_field :iurl, label: "Image URL",readonly: true, class: "input-sm" %>
  <%= f.text_area :htmltemplate, label: "HTML Template",readonly: true, class: "input-sm"  %>
  
  <%= f.number_field :hourly_budget, prepend: "$", input_group_class: 'input-group-sm',readonly: true %>
  <%= f.number_field :daily_budget, prepend: "$", input_group_class: 'input-group-sm',readonly: true %>
  <%= f.number_field :total_basket_value, prepend: "$", input_group_class: 'input-group-sm',readonly: true %>
 
  <%= f.text_field :frequency_spec,  readonly: true  , class: "input-sm"%>
  <%= f.number_field :frequency_expire, append: "minutes" , readonly: true , input_group_class: 'input-group-sm'%>
  <%= f.number_field :frequency_count, readonly: true , class: "input-sm"%> 
  <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @banner.rtb_standards.collect{|i| "#{i.id}" }.join(", "), 
                :label => "Rule IDs",
            } 
  %>     
  
    <%= render :partial => 'showform_textrow', 
            :locals => {
                :value => @banner.exchange_attributes.collect{|i| "#{i.name}=#{i.value}" }.join(", "), 
                :label => "Exchange Attributes",
            } 
  %>
  
<% end %>

app/views/banners/_showform_textrow.html.erb
<div class="form-group">
    <% name="" %>
    <label class="control-label col-sm-2"><%=label%></label>
    <div class="col-sm-10"><%= text_field_tag(name, value, {class:"form-control input-sm", readonly: true }) %></div>
</div>

app/views/banners/_stats.html.erb
<table class="table table-striped table-bordered table-hover">
    <tbody>

    <% if errors = @banner.check_errors and errors.length>0
            str = errors.join("<br/>")
    %>              
        <tr>
            <td>Status</td>
            <td><span class="text text-danger"><%=raw(str)%></span></td>
        </tr>
    <%end%>

    <% if false %>
    <tr>
        <td>Total Cost</td>
        <td><%=number_to_currency(@banner.total_cost)%></td>
    </tr>
    <tr>
        <td>Daily Cost</td>
        <td><%=number_to_currency(@banner.daily_cost)%></td>
    </tr>
    <tr>
        <td>Hourly Cost</td>
        <td><%=number_to_currency(@banner.hourly_cost)%></td>
    </tr>
    <tr>
        <td>Clicks</td>
        <td><%=number_with_delimiter(@banner.clicks)%></td>
    </tr>
    <tr>
        <td>Pixels</td>
        <td><%=number_with_delimiter(@banner.pixels)%></td>
    </tr>
    <tr>
        <td>Wins</td>
        <td><%=number_with_delimiter(@banner.wins)%></td>
    </tr>
    <tr>
        <td>Bids</td>
        <td><%=number_with_delimiter(@banner.bids)%></td>
    </tr>
    <%end%>
    <tr>    
        <td>Last updated</td>
        <td><%=@banner.updated_at%></td>
    </tr>
    <tr>
        <td>Created</td>
        <td><%=@banner.created_at%></td>
    </tr>
    </tbody>
</table> 

app/views/banners/edit.html.erb
 <% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Edit Banner: <em> <%=@banner.name%> </em>
            </div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/banners#">Banners</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Edit</li>
        </ol>
<%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="row mtl">
                <div class="col-md-3">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Profile
                        </div>
                        <div class="panel-body pan">
                            <%= render 'stats' %>
                        </div>
                    </div>
                </div>    
                <div class="col-md-9">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Edit
                        </div>
                        <div class="panel-body pan">
                            <%= render 'form' %>
                            <%= link_to 'Banners', banners_path , class:"btn btn-default btn-sm"%>        
                        </div>
                    </div>                            
                </div>
            </div>
        </div>
<%end%>

app/views/banners/index.html.erb
<% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Banners</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Banners</li>
        </ol>
<%end%>

<% content_for :main_body do %>
      <style>a:focus { color: green !important; }</style>
     <%= link_to 'New Banner', new_banner_path  , class:"btn btn-default btn-sm" %>

      <table class="table table-striped table-hover" id="listtable">
        <thead>
          <tr >
            <th>ID</th>
            <th>Banner Name</th>
            <th>Status</th>
            <th>Campaigns</th>
            <th>Exchanges</th>
            <th width="3%"></th>
            <th width="3%"></th>
            <th width="3%"></th>
          </tr>
        </thead>
        <tbody>
          <% @banners.each do |banner| %>
            <tr>
              <td><%=banner.id%></td>
              <td><%=banner.name%></td>
              <td>
                    <% 
                        if errors = banner.check_errors and errors.length>0
                             str = errors.join("<br/>")
                    %>
                          <span class="text text-danger"><%=raw(str)%></span>
                    <%end%>                          
              </td>   
              <td>
                <% if banner.campaign %>
                    <%= banner.campaign.name%>
                    (<%= link_to "ID #{banner.campaign.id}", edit_campaign_path(banner.campaign)%>)
                  <%end%>
              </td>
              <td>
                    <%= raw(banner.campaign.exchanges.split(",").collect{|e| e.camelize}.join("<br/>")) if banner.campaign and banner.campaign.exchanges %>
              </td>

              <td><%= link_to 'Show',banner %></td>
              <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
              <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
 

<%end%>

app/views/banners/new.html.erb
<% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                New Banner
            </div>
        </div>
    <ol class="breadcrumb page-breadcrumb pull-right">
        <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li><a href="/banners#">Banners</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="active">New</li>
    </ol>
<%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="panel panel-violet">
                <div class="panel-heading">
                    New
                </div>
                <div class="panel-body pan">
                    <%= render 'form' %>
                    <%= link_to 'Banners', banners_path , class:"btn btn-default btn-sm"%>        
                </div>
            </div>                            
        </div>
<%end%>

app/views/banners/show.html.erb
<% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Show Banner: <em> <%=@banner.name%> </em></div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/banners#">Banners</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Show</li>
        </ol>
<%end%>
<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="row mtl">
                <div class="col-md-3">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Profile
                        </div>
                        <div class="panel-body pan">
                            <%= render 'stats' %>
                        </div>
                    </div>
                </div>    
                <div class="col-md-9">
                    <div class="panel panel-grey">
                        <div class="panel-heading">
                            Show
                        </div>
                        <div class="panel-body pan">
                            <%= render 'showform' %>
                            <%= link_to 'Edit', edit_banner_path(@banner) , class:"btn btn-default btn-sm" %> |
                            <%= link_to 'Banners', banners_path , class:"btn btn-default btn-sm"%>        
                        </div>
                    </div>                            
                </div>
            </div>
        </div>
<%end%>