config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :campaigns
  resources :banners
  resources :banner_videos
  resources :targets
  resources :rtb_standards
  resources :documents
  resources :categories
  resources :users
  resources :attachments
  resources :lists

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/myaccount' => 'users#myaccount'
  patch '/myaccountUpdate' => 'users#myaccountUpdate'
  
  root 'dashboards#home'
  get '/' => 'dashboards#home'
  get 'dashboards/campaigndetail' => 'dashboards#campaigndetail'  
  
  get 'dashboards' => 'dashboards#home'
  get 'dashboards/home' => 'dashboards#home'
  
  get 'reports' => 'reports#home'
  get 'reports/home' => 'reports#home'
  
  get 'getCampaignDates' => 'campaigns#getDates'
  get 'getExchangeAttributes' => 'campaigns#getExchangeAttributes'
  get 'biddersSynchAll' => 'campaigns#biddersSynchAll'
  
  get 'duplicatedoc' => 'documents#duplicate'
  get 'duplicatertb_standard' => 'rtb_standards#duplicate'  
  
  get 'help' => 'help#list'
  get 'help/list' => 'help#list'
  get 'help/open' => 'help#open'
  
  post '/attachments/create' => 'attachments#create'
  
  post "/lists/upload" => "lists#upload"


 namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
      namespace :report do
        post 'summary'
        get 'summary'
      end
    end
  end  
  
end

app/models/document.rb
class Document  < ActiveRecord::Base

    has_and_belongs_to_many :categories

    before_update :set_updated_at

    def set_updated_at
       self.updated_at = Time.now         
    end

end

__END__

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

    before_action :set_document, only: [:show, :edit, :update, :destroy ]

	before_filter :authorize


    def index
        @documents = Document.order(:name)
    end

    def show
    end

    def new
        @document = Document.new
    end

    def edit
    end

    def create
        @document = Document.new(document_params)
        respond_to do |format|
            if @document.save
                format.html { redirect_to edit_document_path(@document), notice: 'Document was successfully created.' }
                format.json { render :edit, status: :created, location: @document }
            else
                format.html { render :new }
                format.json { render json: @document.errors, status: :unprocessable_entity }
            end
        end
    end

    def duplicate
        @document = Document.find(params[:id]).dup
        @document.name = "#{@document.name} Copy"
        respond_to do |format|
            if @document.save
                format.html { redirect_to documents_path, notice: 'Document was successfully duplicated.' }
                format.json { render :edit, status: :created, location: @document }
            else
                format.html { render :new }
                format.json { render json:@document.errors, status: :unprocessable_entity }
            end
        end        
        
    end

    def update
        respond_to do |format|
            if @document.update(document_params)
                format.html { redirect_to edit_document_path(@document), notice: 'Document was successfully updated.' }
                format.json { render :show, status: :ok, location: @document }
            else
                format.html { render :edit }
                format.json { render json: @document.errors, status: :unprocessable_entity }
            end
        end
    end


    def destroy
        @document.destroy
        respond_to do |format|
            format.html { redirect_to documents_path, notice: 'Document was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

	def copyOneList
		obj = TapScript.new();		
		if id = params["submit"] then 			
			if newDoc = obj.copyOne(id,current_user.id.to_s) then 
				obj.add(newDoc);		
			end
		end
		list	
		render "list"
	end


	def save
		params.each { |k,v| puts "#{k}=#{v}"  }
		newDoc = {
			:name=>params[:name],
			:description=>params[:description],
			:user_ref => current_user.id.to_s,
			:type=>params[:type],
			:code=>params[:code],
		}
		obj = TapScript.new();
		obj.update(params[:id],newDoc) ;
		list
		render "list"
	end




    private

    def set_document
        @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :updated_at,:created_at,:description, :doctype,
        :code, :category_ids=>[])
    end





end


__END__

app/views/documents/_form.html.erb
<style>
	#editor_container { 
		border: 1px;
		border-radius: 6px 6px 6px 6px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.075);	
		width:100%; 
		height:400px;	
		padding: 0.5em;
	}
	#editor { 
		position:relative;
		width:100%; 
		height:100%;
	}		
</style>

<%= bootstrap_form_for(@document, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-11") do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2
      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :name, label: "Name" , class: "input-sm" %>
  <%= f.text_field :description, class: "input-sm" %>
  <%= f.hidden_field :doctype, value: "html" %>
  <%= f.collection_select(:category_ids, Category.order(:name), :id, :name, {label: "Categories"},
    {:multiple => true, class: "search_categories form-control" }) %>  
	  <span style="display:none"><%= f.text_area :code, label: " " %></span>
	  
    <%= f.submit  class: "btn btn-default btn-sm" %>
    <%= link_to 'Cancel', documents_path , class: "btn btn-default btn-sm" %> 
  
	<div id="editor_container">
		<div name="editor" id="editor"></div>
	</div>  
  
<% end %>

app/views/documents/edit.html.erb
<% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Edit Document: <em> <%=@document.name%> </em>
            </div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/documents#">Documents</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Edit</li>
        </ol>
<%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
<%end%>

app/views/documents/index.html.erb
<% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Documents</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Documents</li>
        </ol>
<%end%>

<% content_for :main_body do %>

      <table class="table table-striped table-hover ">
        <thead>
          <tr >
            <th>Document Name</th>
            <th>Description</th>
            <th>Assigned Categories</th>
            <th>Updated</th>
            <th colspan="4" width="10%"></th>
          </tr>
        </thead>
        <tbody>
          <% @documents.each do |document| %>
            <tr>
              <td><%=document.name%></td>
              <td><%=document.description%></td>
              <td>
				         <% document.categories.each do |category| %>
                    <%= link_to category.name, category_path(category)%>
                  <%end%>
              </td>
              <td><%=document.updated_at.strftime("%b %e %H:%M %Z %Y")%></td>
              <td><%= link_to 'Edit', edit_document_path(document) %></td>
              <td><%= link_to 'Show', help_open_path(:id=>document.id)%></td>
              <td><%= link_to 'Duplicate', duplicatedoc_path(:id=>document.id) %></td>
              <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      <%= link_to 'New Document', new_document_path  , class:"btn btn-default btn-sm" %>
      
<%end%>

app/views/documents/new.html.erb
<% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                New Document: <em> <%=@document.name%> </em>
            </div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/documents#">Documents</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">New</li>
        </ol>
<%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
<%end%>