config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :campaigns
  resources :banners
  resources :banner_videos
  resources :targets
  resources :rtb_standards
  resources :documents
  resources :categories
  resources :users
  resources :attachments
  resources :lists

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/myaccount' => 'users#myaccount'
  patch '/myaccountUpdate' => 'users#myaccountUpdate'
  
  root 'dashboards#home'
  get '/' => 'dashboards#home'
  get 'dashboards/campaigndetail' => 'dashboards#campaigndetail'  
  
  get 'dashboards' => 'dashboards#home'
  get 'dashboards/home' => 'dashboards#home'
  
  get 'reports' => 'reports#home'
  get 'reports/home' => 'reports#home'
  
  get 'getCampaignDates' => 'campaigns#getDates'
  get 'getExchangeAttributes' => 'campaigns#getExchangeAttributes'
  get 'biddersSynchAll' => 'campaigns#biddersSynchAll'
  
  get 'duplicatedoc' => 'documents#duplicate'
  get 'duplicatertb_standard' => 'rtb_standards#duplicate'  
  
  get 'help' => 'help#list'
  get 'help/list' => 'help#list'
  get 'help/open' => 'help#open'
  
  post '/attachments/create' => 'attachments#create'
  
  post "/lists/upload" => "lists#upload"


 namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
      namespace :report do
        post 'summary'
        get 'summary'
      end
    end
  end  
  
end

app/models/rtb_standard.rb
class RtbStandard < ActiveRecord::Base

    belongs_to :campaign
    has_many :banners
    has_many :banner_videos
    has_and_belongs_to_many :campaigns
    has_and_belongs_to_many :banners
    has_and_belongs_to_many :banner_videos

    #  operand_list_id
    belongs_to :list, :foreign_key => :operand_list_id
   
    validates :name,:rtbspecification, :presence => true
   
   before_update :set_updated_at
   after_update :set_campaigns_updated_at
   after_create :set_campaigns_updated_at
   
    def set_updated_at
       self.updated_at = Time.now         
    end

   def set_campaigns_updated_at       
        if campaigns = self.campaigns
            campaigns.each { |campaign| 
                campaign.set_updated_at
                campaign.save
            }
        end
    end
    
end

app/controllers/rtb_standards_controller.rb
class RtbStandardsController < ApplicationController

  before_action :set_rtb_standard, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  
  # GET /rtb_standards
  # GET /rtb_standards.json
  def index
    @rtb_standards = RtbStandard.order(:name)
  end

  # GET /rtb_standards/1
  # GET /rtb_standards/1.json
  def show
  end

  # GET /rtb_standards/new
  def new
    @rtb_standard = RtbStandard.new
    @rtb_standard.rtb_required ||= true
  end

  # GET /rtb_standards/1/edit
  def edit
  end

  # POST /rtb_standards
  # POST /rtb_standards.json
  def create
    @rtb_standard = RtbStandard.new(rtb_standard_params)
    respond_to do |format|
      if @rtb_standard.save
        # No need to update campaigns. Targets are assigned in Campaign edit.
        format.html { redirect_to @rtb_standard, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rtb_standard }
      else
        format.html { render :new }
        format.json { render json: @rtb_standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rtb_standards/1
  # PATCH/PUT /rtb_standards/1.json
  def update
    respond_to do |format|
      old_camp_ids = []
      old_camp_ids += @rtb_standard.campaigns.collect{|c| c.id.to_s} if @rtb_standard.campaigns
      old_camp_ids += @rtb_standard.banners.collect{|b| b.campaign.id.to_s } if @rtb_standard.banners
      old_camp_ids += @rtb_standard.banner_videos.collect{|c| c.campaign.id.to_s } if @rtb_standard.banner_videos
      puts "Old campaigns #{old_camp_ids}"
      if @rtb_standard.update(rtb_standard_params)
        notice = 'Rule was successfully updated.'
        new_camp_ids =[]
        new_camp_ids += @rtb_standard.campaigns.collect{|c| c.id.to_s} if @rtb_standard.campaigns
        new_camp_ids += @rtb_standard.banners.collect{|b| b.campaign.id.to_s } if @rtb_standard.banners
        new_camp_ids += @rtb_standard.banner_videos.collect{|c| c.campaign.id.to_s } if @rtb_standard.banner_videos
        puts "New campaigns #{old_camp_ids}"
        new_camp_ids += old_camp_ids
        new_camp_ids.uniq!   # List all campaigns to update
        # Update bidder for old and new campaign 
        new_camp_ids.each do |id|              
            if id and campaign = Campaign.find_by_id(id) 
              puts "Update campaign #{id}, name #{campaign.name}"
              if not campaign.update_bidder
                notice += ' <span class="text-danger">Error on bidder synch process. Please try again.</span>'
                break
              end
            else 
              puts "Can't find campaign #{id}"
            end
        end                 
        format.html { redirect_to @rtb_standard, notice: notice }
        format.json { render :show, status: :ok, location: @rtb_standard }
      else
        format.html { render :edit }
        format.json { render json: @rtb_standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rtb_standards/1
  # DELETE /rtb_standards/1.json
  def destroy
    notice = ""
    if not Bidder.ping
      notice = '<span class="text-danger">Error. Unable to connect to bidder. Check staus and try again.</span>'
    else  
        old_camp_ids = []
        old_camp_ids += @rtb_standard.campaigns.collect{|c| c.id.to_s} if @rtb_standard.campaigns
        old_camp_ids += @rtb_standard.banners.collect{|b| b.campaign.id.to_s } if @rtb_standard.banners
        old_camp_ids += @rtb_standard.banner_videos.collect{|c| c.campaign.id.to_s } if @rtb_standard.banner_videos
        puts "Old campaigns #{old_camp_ids}"
        old_camp_ids.uniq!   # List all campaigns to update
      if @rtb_standard.destroy
        notice += 'Rule was successfully destroyed.'
        # Update bidder for old and new campaign 
        old_camp_ids.each do |id|              
            if id and campaign = Campaign.find_by_id(id) 
              puts "Update campaign #{id}, name #{campaign.name}"
              campaign.update_bidder
            else 
              puts "Can't find campaign #{id}"
            end
        end
      else
        notice += '<span class="text-danger">Database error. Please try again.</span>'  
      end
    end
    respond_to do |format|
      format.html { redirect_to rtb_standards_url, notice: notice }
      format.json { head :no_content }
    end
  end

    def duplicate
        @rtb_standard = RtbStandard.find(params[:id]).dup
        @rtb_standard.name = "#{@rtb_standard.name} Copy"
        respond_to do |format|
            if @rtb_standard.save
                format.html { redirect_to rtb_standards_path, notice: 'Rule was successfully duplicated.' }
                format.json { render :edit, status: :created, location: @rtb_standard }
            else
                format.html { render :new }
                format.json { render json:@rtb_standard.errors, status: :unprocessable_entity }
            end
        end        
        
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rtb_standard
      @rtb_standard = RtbStandard.find(params[:id])
    end


    def rtb_standard_params
      
      # Check if a list is referenced
      if params[:rtb_standard] and not params[:rtb_standard][:operand_list_id].to_s.empty? and list=List.find_by_id(params[:rtb_standard][:operand_list_id])        
        params[:rtb_standard][:operand] = "$#{list.name}"
      end
      
      params.require(:rtb_standard).permit(:rtbspecification,:name, :description, :operator, :operand, :operand_type, :operand_list_id,
        :operand_ordinal, :rtb_required, :created_at, :updated_at )
    end





end

app/views/rtb_standards/_form.html.erb
<%= bootstrap_form_for(@rtb_standard,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <% if @rtb_standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rtb_standard.errors.count, "error") %> prohibited this rule from being saved:</h2
      <ul>
      <% @rtb_standard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.text_field :name, label: "Rule Name" , class: "input-sm" %>
  <%= f.text_field :id, label: "Rule ID" , class: "input-sm", readonly: true %>
  <%= f.text_area :description, label: "Description" , class: "input-sm" %>

  <%= f.select :rtbspecification, 
        ExchangeRtbspecs.order("rtbspecification").collect { |v|
          [ v[:rtbspecification], v[:rtbspecification] , {:operand_type =>v[:operand_type], :operand_ordinal =>v[:operand_ordinal] }] 
          }.unshift(["",""]),          # Push blank option to allow placeholder on new init
          {},{class: "input-sm select2_single form-control"} 
  %>  

  <%= f.select :operator, RtbStandardOperator.all.collect { |v| [ v[:name], v[:name] ] },{ include_blank: true}, {class: "input-sm nosearch"} %>  
  
  <%= f.text_field :operand, label:"Operand value", class: 'input-sm' %>
  <%= f.select :operand_list_id, List.all.collect { |v| [ v[:name], v[:id] ] },{ label: "Use Set as Operand",include_blank: true}, {class: "input-sm search"} %>  

  <%= f.select :operand_type, [ ["Integer","I"],["String","S"],["Double","D"] ] ,{ "include_blank" => true}, 
      {class: "input-sm nosearch" } %> 
  <%= f.select :operand_ordinal, [ ["Scalar","S"],["List","L"] ] ,{ include_blank: true}, {class: "input-sm nosearch"} %> 



  <div class="form-group"><label class="control-label col-sm-2" for="user_admin">RTB Required</label>
    <div class="col-sm-10">
        <%= f.check_box :rtb_required, label: ""  %>
    </div>
  </div>  
  <div class="actions">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <button type="submit" class="btn btn-default btn-sm">Update</button>
    </div>
  </div>  
  
<% end %>

app/views/rtb_standards/_form_csv.html.erb
 <div class="form-group">
    <label class="control-label col-sm-2" for="<%=tag_id%>"><%=label%></label>
    <div class="col-sm-10">
      <%= select_tag tag_id,
          options_for_select( 
            collection,
            value.to_s.split(",")
          ), 
          { include_blank: "Select a #{label}",  multiple: "multiple", class:"form-control"} 
      %>
    </div>
  </div>

app/views/rtb_standards/_showform.html.erb
<%= bootstrap_form_for(@rtb_standard,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <% if @rtb_standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rtb_standard.errors.count, "error") %> prohibited this rule from being saved:</h2
      <ul>
      <% @rtb_standard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.text_field :name, label: "Rule Name" , class: "input-sm" ,readonly: true%>
  <%= f.text_field :id, label: "Rule ID" , class: "input-sm", readonly: true %>
  <%= f.text_area :description, label: "Description" , class: "input-sm" ,readonly: true%>

  <%= f.text_field :rtbspecification, class: "input-sm" ,readonly: true%>
  <%= f.text_field :operator, class: "input-sm" ,readonly: true%>
  <%= f.text_field :operand, class: 'input-sm' ,readonly: true%>
  <%= f.text_field :operand_type, class: 'input-sm',readonly: true %>
  <%= f.text_field :operand_ordinal, class: 'input-sm',readonly: true %>
  <div class="form-group"><label class="control-label col-sm-2" for="user_admin">RTB Required</label>
    <div class="col-sm-10">
        <%= f.check_box :rtb_required, label: "" , disabled: true %>
    </div>
  </div>  
  
<% end %>

app/views/rtb_standards/_showform_textrow.html.erb
<div class="form-group">
    <% name="" %>
    <label class="control-label col-sm-2"><%=label%></label>
    <div class="col-sm-10"><%= text_field_tag(name, value, {class:"form-control input-sm", readonly: true }) %></div>
</div>

app/views/rtb_standards/_stats.html.erb
<table class="table table-striped table-bordered table-hover">
    <tbody>
    <tr>
        <td>Last updated</td>
        <td><%=@rtb_standard.updated_at%></td>
    </tr>
    <tr>
        <td>Created</td>
        <td><%=@rtb_standard.created_at%></td>
    </tr>
    </tbody>
</table> 

app/views/rtb_standards/edit.html.erb
 <% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                Edit Rule: <em> <%=@rtb_standard.name%> </em></div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/rtb_standards#">Rules</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Edit</li>
        </ol>
 <%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="row mtl">
                <div class="col-md-3">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Profile
                        </div>
                        <div class="panel-body pan">
                            <%= render 'stats' %>
                        </div>
                    </div>
                </div>    
                <div class="col-md-9">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Edit
                        </div>
                        <div class="panel-body pan">
                            <%= render 'form' %>
                            <%= link_to 'Rules', rtb_standards_path , class:"btn btn-default btn-sm"%>        
                        </div>
                    </div>                            
                </div>
            </div>
        </div>

<%end%>

app/views/rtb_standards/index.html.erb
 <% content_for :breadcrumb do %> 
        <div class="page-header pull-left">
            <div class="page-title">
                Rules</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Rules</li>
        </ol>
<%end%>

<% content_for :main_body do %> 
      <style>a:focus { color: green !important; }</style>
      <%= link_to 'New rule', new_rtb_standard_path  , class:"btn btn-default btn-sm" %>
      <table class="table table-striped table-hover" id="listtable">
        <thead>
          <tr >            
            <th>ID</th>
            <th>Rule Name</th>
            <th>Campaigns</th>
            <th>Banners</th>
            <th>Videos</th>
            <th width="3%"></th>
            <th width="3%"></th>
            <th width="3%"></th>
            <th width="3%"></th>
          </tr>
        </thead>
        <tbody>
          <% @rtb_standards.each do |rtb_standard| %>
            <tr>
              <td><%=rtb_standard.id%></td>
              <td><%=rtb_standard.name%></td>
              <td>
                  <%if rtb_standard.campaigns  %>
                      <% rtb_standard.campaigns.each do |camp| %>
                         <%=camp.name%> (<%= link_to "ID #{camp.id}", campaign_path(camp)%>)<br/>                    
                     <%end%>
                  <%end%>
              </td>
              <td>
                  <%if rtb_standard.banners  %>
                      <% rtb_standard.banners.each do |banner| %>
                         <%=banner.name%> (ID <%= link_to "ID #{banner.id}", banner_path(banner)%>)<br/>                    
                     <%end%>
                  <%end%>
              </td>
              <td>
                  <%if rtb_standard.banner_videos  %>
                      <% rtb_standard.banner_videos.each do |banner_video| %>
                         <%=banner_video.name%> (<%= link_to "ID #{banner_video.id}", banner_video_path(banner_video)%>)<br/>                    
                     <%end%>
                  <%end%>
              </td>              
              <td><%= link_to 'Show',rtb_standard   %></td>
              <td><%= link_to 'Edit', edit_rtb_standard_path(rtb_standard)  %></td>
              <td><%= link_to 'Duplicate', duplicatertb_standard_path(:id=>rtb_standard.id) %></td>
              <td><%= link_to 'Destroy', rtb_standard, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      

<%end%>

app/views/rtb_standards/new.html.erb
<% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                New Rule
            </div>
        </div>
    <ol class="breadcrumb page-breadcrumb pull-right">
        <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li><a href="/rtb_standards#">Rules</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="active">New</li>
    </ol>
<%end%>

<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="panel panel-violet">
                <div class="panel-heading">
                    New
                </div>
                <div class="panel-body pan">
                    <%= render 'form' %>
                    <%= link_to 'Rules', rtb_standards_path , class:"btn btn-default btn-sm"%>        
                </div>
            </div>                            
        </div>
<%end%>

app/views/rtb_standards/show.html.erb
<% content_for :breadcrumb do %> 	
        <div class="page-header pull-left">
            <div class="page-title">
                Show Rule: <em> <%=@rtb_standard.name%> </em></div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="/">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li><a href="/rtb_standards#">Rules</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Show</li>
        </ol>
<%end%>
<% content_for :main_body do %> 	
        <div class="col-md-12"><h3></h3>
            <div class="row mtl">
                <div class="col-md-3">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Profile
                        </div>
                        <div class="panel-body pan">
                            <%= render 'stats' %>
                        </div>
                    </div>
                </div>    
                <div class="col-md-9">
                    <div class="panel panel-grey">
                        <div class="panel-heading">
                            Show
                        </div>
                        <div class="panel-body pan">
                            <%= render 'showform' %>
                             <%= link_to 'Edit', edit_rtb_standard_path(@rtb_standard) , class:"btn btn-default btn-sm" %> |
                             <%= link_to 'Rules', rtb_standards_path , class:"btn btn-default btn-sm"%>            
                        </div>
                    </div>                            
                </div>
            </div>
        </div>
<%end%>